version: 2

updates:
  - package-ecosystem: npm
    directory: /examples/
    exclude-paths:
      - /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      serde:
        patterns:
          - serde
          - serde*
