version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  groups:
    eslint-typescript:
      patterns:
      - '@eslint/js'
      - eslint
      - eslint-plugin-react-hooks
      - eslint-plugin-react-refresh
      - typescript
      - typescript-eslint
    react:
      patterns:
      - '@types/react'
      - '@types/react-dom'
      - react
      - react-dom
    vite:
      patterns:
      - '@vitejs/plugin-react'
      - vite
