version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  groups:
    cors:
      patterns:
      - '@types/cors'
      - cors
    express:
      patterns:
      - '@types/express'
      - express
    types:
      patterns:
      - '@types/node'
