version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  groups:
    apollo-server-express-graphql:
      patterns:
      - '@apollo/server'
      - '@as-integrations/express5'
      - '@types/express'
      - express
      - graphql
    cors:
      patterns:
      - '@types/cors'
      - cors
